name: Publish Docker Image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages and Dockerhub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Derive Git Tag
        id: derive-git-tag
        run: echo "::set-output name=tag::$(git describe --tags)"
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ github.repository }}:${{ steps.derive-git-tag.outputs.tag }}
            ${{ github.repository }}:latest
      - name: Build & Push to GHCR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.derive-git-tag.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest